# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: pm

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -X github.com/rprtr258/pm/internal/core.Version={{.Version}}

archives:
  - formats: binary
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    files: [none*] # NOTE: hack to exclude README.md and LICENSE which are for some reason are always included even if this list is empty blyat

checksum:
  disable: true
